### ISSUE TITLE
README suggestion

### ISSUE THREAD

**Issue by jemacom** [evilsocket/arc#85]
I think it's worth mention the requirements to properly build the project. For example this project won't compile with earlier Go version than 1.8

It'll show these errors:
```
➜  arcd git:(master) make
# github.com/evilsocket/arc/arcd/db
db/db.go:31: undefined: sort.Slice
db/db.go:80: undefined: sort.Slice
Makefile:22: recipe for target 'build' failed
make: *** [build] Error 2
```
